# Generated by Django 3.2.6 on 2021-08-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorIndex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlisting',
            name='error_description',
            field=models.TextField(default=''),
        ),
    ]
